### ISSUE TITLE
Provide a way to request old-style authentication

### ISSUE THREAD

**Issue by MikeTaylor** [indexdata/foliojs#4]
FOLIO is transitioning from old-style token-bases authentication to new-style cookie-based authentication with session expiry. The FolioJS library implements both, favouring the new style when the back-end support it.

We should have a way for client code to request that old-style authentication is used. This might be an extra parameter to the `session.login` method (and a corresponding extra parameter to the `service.login` method). Or perhaps an environment variables would be better.

@dcrossleyau @wafschneider @funkymalc @ihardy  Which would be more useful for you?

**Comment by wafschneider** [comment]
I wonder if an environment variable would be better, so client code actually doesn't need to care, and it can be a runtime decision by the operator.

**Comment by MikeTaylor** [comment]
I'm coming to that conclusion, yes: it's what I did for #3.

**Comment by dcrossleyau** [comment]
Using an environment variable.

**Comment by MikeTaylor** [comment]
Thanks, it'll be so!
